output: ../chains/mcmc

sampler: !defaults [../sampler/mcmc]

theory: !defaults [../theory/dm_gomp]
likelihood: !defaults [../likelihood/cmb, ../likelihood/gomp_qdw, ../likelihood/lens, ../likelihood/bao]
prior: !defaults [../prior/cmb]
params: !defaults [../params/cosmo, ../params/gomp, ../params/Mnu, ../params/DM]

debug: false
stop_at_error: false
